version: '3.8'

services:
    worker:
        build: .
        command: celery -A workers.thumbnail worker --loglevel=info
        environment:
            - BROKER=amqp://guest:guest@rabbitmq:5672//
            - BACKEND=rpc://
        volumes:
            - /tmp/static:/tmp/static
        depends_on: 
            - rabbitmq
    
    rabbitmq:
        image:  rabbitmq:management-alpine
        ports:
            - 5672:5672
            - 15672:15672

    flower:
        image: mher/flower
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
            - FLOWER_PORT=8888
        ports:
            - 8888:8888
        depends_on: 
            - rabbitmq
            - worker
        