version: '3.8'

services: 
    webapp:
        build: .
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        volumes: 
            - /tmp/static:/tmp/static