version: '3.8'

services:
    backend:
        build:
            context: .
            dockerfile: backend.Dockerfile
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        environment:
            - BROKER=amqp://guest:guest@rabbitmq:5672//
            - BACKEND=rpc://
        ports:
        - 8000:8000
        volumes: 
        - /tmp/static:/tmp/static
    worker:
        build:
            context: .
            dockerfile: worker.Dockerfile
        command: celery -A workers.thumbnail worker --loglevel=info
        environment:
            - BROKER=amqp://guest:guest@rabbitmq:5672//
            - BACKEND=rpc://
        volumes:
            - /tmp/static:/tmp/static
        depends_on: 
            - rabbitmq
    
    rabbitmq:
        image:  rabbitmq:management-alpine
        ports:
            - 5672:5672
            - 15672:15672

    flower:
        image: mher/flower
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
            - FLOWER_PORT=8888
        ports:
            - 8888:8888
        depends_on: 
            - rabbitmq
            - worker
        